FROM node:18 AS build

WORKDIR /app

COPY package*.json /app/

RUN npm install

COPY . /app/

RUN ls -l /app

RUN npm run build -- --base-href /air-pollution/

RUN ls -l /app/dist/frontend

FROM nginx:alpine

COPY --from=build /app/dist/frontend/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
